---
title: "100 species comparison"
output: html_document
date: "2023-10-09"
---

# Setup

```{r setup}
library(tidyverse)
library(forcats)
library(cowplot)
library(agricolae)
library(ggupset)
library(RColorBrewer)
library(patchwork)
library(vegan)
library(pheatmap)
library(ggradar)
library(broom)
```


```{r}
data <- targets::tar_read(merged_all_results)
# rename BLAST to BLAST97 to differentiate from BLAST100 (percentage identity in both cases)
data <- data |> mutate(Type = str_replace(Type, '^BLAST$', 'BLAST97'))
truth <- targets::tar_read(truth_set_data)
```

Let's remove the >0.2 Kraken runs, those are too strict

```{r}
data <- data |> filter(!Type %in% c('Kraken_0.2', 'Kraken_0.3', 'Kraken_0.4', 'Kraken_0.5', 'Kraken_0.6', 'Kraken_0.7', 'Kraken_0.8', 'Kraken_0.9'))
```

Made a mistake- Metabuli's Database is misspelled

```{r}
data <- data |> mutate(Subject = str_replace_all(Subject, pattern = '_ref.fasta', replacement=''))
```



```{r}
table(data$Query)
```

# Negative greengenes

No 12S. Only 16S.

## 16S

There is no Truth. Should all be NA.

```{r}
greengenes_data <- data |> filter(Query == 'make_12s_16s_simulated_reads_6-fakeGenes_GreenGenes_RESULTS_dada2_asv.fa', Subject == '16S_v04_final.fasta')
```

```{r}
greengenes_data |> filter(!is.na(species))
```
No hits :) 



## 16S exclusion databases

```{r}

sixteen_exclusions <- data |> filter(str_starts(Subject, '16S_v04_final.fasta_Taxonomies.')) |> 
  filter(Query == 'make_12s_16s_simulated_reads_6-fakeGenes_GreenGenes_RESULTS_dada2_asv.fa')
table(sixteen_exclusions$Subject)
sixteen_exclusions_split <- sixteen_exclusions |> separate(Subject, into = c('before', 'hit'), sep='.txt_') |> 
  # get rid of leftover non-subsetted databases
  filter(!is.na(hit)) |> 
  separate(hit, into=c('Database', 'after'), sep='_subset')
```

```{r}
sixteen_exclusions_split |> filter(!is.na(species)) |> 
  mutate(Database = case_when(Database == 'thirty' ~ '30%',
                              Database == 'fifty' ~ '50%',
                              Database == 'seventy' ~ '70%')) |> 
  group_by(Type, Database, after) |>
  summarise(counts = n()) |> 
  ggplot(aes(x = Database, group = interaction(Database, Type), fill = Type, y = counts)) + geom_boxplot(outlier.shape=NA) + 
  geom_point(position = position_jitterdodge(), alpha=0.5, aes(color=Type)) +
  theme_minimal() + 
  ylab("False positive species") +
  theme(legend.position = 'bottom')
```

```{r}
sixteen_exclusions_split |> filter(!is.na(species)) |> 
  mutate(Database = case_when(Database == 'thirty' ~ '30%',
                              Database == 'fifty' ~ '50%',
                              Database == 'seventy' ~ '70%')) |> 
  group_by(Type, Database) |> 
  summarise(species = paste(unique(species), sep = ',', collapse=', ' ))
```

## Doublecheck with 12S

12S should have even fewer hits, but let's check!

```{r}
greengenes_data_12S <- data |> filter(Query == 'make_12s_16s_simulated_reads_6-fakeGenes_GreenGenes_RESULTS_dada2_asv.fa', Subject == '12s_v010_final.fasta')
greengenes_data_12S |> filter(!is.na(species))
```
Good.

```{r}
twelve_exclusions <- data |> filter(str_starts(Subject, '12s_v010_final.fasta_')) |> 
  filter(Query == 'make_12s_16s_simulated_reads_6-fakeGenes_GreenGenes_RESULTS_dada2_asv.fa')
table(sixteen_exclusions$Subject)

twelve_exclusions_split <- twelve_exclusions |> separate(Subject, into = c('before', 'hit'), sep='.txt_') |> 
  # get rid of leftover non-subsetted databases
  filter(!is.na(hit)) |> 
  separate(hit, into=c('Database', 'after'), sep='_subset')

twelve_exclusions_split |> filter(!is.na(species)) |> 
  mutate(Database = case_when(Database == 'thirty' ~ '30%',
                              Database == 'fifty' ~ '50%',
                              Database == 'seventy' ~ '70%')) |> 
  group_by(Type, Database, after) |>
  summarise(counts = n()) |> 
  ggplot(aes(x = Database, group = interaction(Database, Type), color = Type, y = counts)) + geom_boxplot() + 
  geom_point(position = position_jitterdodge(), alpha=0.5) +
  theme_minimal() + 
  ylab("False positive species")
```

Nothing. Good!